$axure.loadCurrentPage({
  "url":"ntp配置.html",
  "generationDate":new Date(1525998071484.69),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bd2dfb2cba5546279863a77ca210c164",
    "type":"Axure:Page",
    "name":"NTP配置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f0162cb54f08417fb951ca23d987eff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":100,
              "y":80},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08327ce039414b76a8044c57d38dd2fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":100,
                  "y":80},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a4fedc4c59341e39e13b567e9ed8848",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":102,
              "y":116},
            "size":{
              "width":76,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"374e68f78bba42429c2a38716b1aee4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":102,
                  "y":116},
                "size":{
                  "width":76,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da072b61436e4b1da866b7e3e6b0552c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":190,
              "y":115},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"77e417ea7bf04d558e188f8e0567b5d8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":191,
              "y":146},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"66e583dc19ae4030872f162d844a207f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":101,
              "y":149},
            "size":{
              "width":76,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"300c3ab26875400baa9803d324600c51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":101,
                  "y":149},
                "size":{
                  "width":76,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3585afe6b9c47388bac285aaf6f4ab4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":104,
              "y":182},
            "size":{
              "width":76,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"955ec29530844efda0dd577ea5142c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":104,
                  "y":182},
                "size":{
                  "width":76,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2dc01e53b59a436eb207eb3a9bf8ee79",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":192,
              "y":181},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0083cfcbf1054ff5b2f6732920b9b24a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":193,
              "y":212},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b8cc70ab1cb94913a49077e311b5dc11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":103,
              "y":215},
            "size":{
              "width":76,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7fe8e588fa44869a3d5f73f4b107538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":103,
                  "y":215},
                "size":{
                  "width":76,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f57095d8aef64432956ef345b7bb0539",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":106,
              "y":245},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5e5dbe9e7dc409e8a6db0d619025628",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":106,
                  "y":245},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96c7dc2e68ce4f5bad3c59c22f9a9fae",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":194,
              "y":244},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"db24c3cf5d10421fa02a838577124f5b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":195,
              "y":275},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"00682dd2c8fe41e9a6773389fee83d38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":105,
              "y":278},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"106a2771af3248d3b295ba964614baf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":105,
                  "y":278},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf3befdb9381423a9f516a54837db1bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":418,
              "y":282},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2358ee7bd3c348f493724ee2fa25539c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":418,
                  "y":282},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1d1fc7c4f794803987a2a8de6319168",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":104,
              "y":320},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c984e7c50f074792a3f42fb5ee4626ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":104,
                  "y":320},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99e986ae1408498a9ea43e22c5967dd6",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":210,
              "y":323},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0949439164b34cdb85c2c28f1245346e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":210,
                  "y":323},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"8d55861c7d454c9e8bfc2a96ec5ed85f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":350,
              "y":323},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26ef8b5d4bb94ff89f72ef8989549dba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":350,
                  "y":323},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "f0162cb54f08417fb951ca23d987eff6":{
      "scriptId":"u0"},
    "08327ce039414b76a8044c57d38dd2fd":{
      "scriptId":"u1"},
    "3a4fedc4c59341e39e13b567e9ed8848":{
      "scriptId":"u2"},
    "374e68f78bba42429c2a38716b1aee4b":{
      "scriptId":"u3"},
    "da072b61436e4b1da866b7e3e6b0552c":{
      "scriptId":"u4"},
    "77e417ea7bf04d558e188f8e0567b5d8":{
      "scriptId":"u5"},
    "66e583dc19ae4030872f162d844a207f":{
      "scriptId":"u6"},
    "300c3ab26875400baa9803d324600c51":{
      "scriptId":"u7"},
    "d3585afe6b9c47388bac285aaf6f4ab4":{
      "scriptId":"u8"},
    "955ec29530844efda0dd577ea5142c8c":{
      "scriptId":"u9"},
    "2dc01e53b59a436eb207eb3a9bf8ee79":{
      "scriptId":"u10"},
    "0083cfcbf1054ff5b2f6732920b9b24a":{
      "scriptId":"u11"},
    "b8cc70ab1cb94913a49077e311b5dc11":{
      "scriptId":"u12"},
    "c7fe8e588fa44869a3d5f73f4b107538":{
      "scriptId":"u13"},
    "f57095d8aef64432956ef345b7bb0539":{
      "scriptId":"u14"},
    "b5e5dbe9e7dc409e8a6db0d619025628":{
      "scriptId":"u15"},
    "96c7dc2e68ce4f5bad3c59c22f9a9fae":{
      "scriptId":"u16"},
    "db24c3cf5d10421fa02a838577124f5b":{
      "scriptId":"u17"},
    "00682dd2c8fe41e9a6773389fee83d38":{
      "scriptId":"u18"},
    "106a2771af3248d3b295ba964614baf4":{
      "scriptId":"u19"},
    "cf3befdb9381423a9f516a54837db1bd":{
      "scriptId":"u20"},
    "2358ee7bd3c348f493724ee2fa25539c":{
      "scriptId":"u21"},
    "d1d1fc7c4f794803987a2a8de6319168":{
      "scriptId":"u22"},
    "c984e7c50f074792a3f42fb5ee4626ec":{
      "scriptId":"u23"},
    "99e986ae1408498a9ea43e22c5967dd6":{
      "scriptId":"u24"},
    "0949439164b34cdb85c2c28f1245346e":{
      "scriptId":"u25"},
    "8d55861c7d454c9e8bfc2a96ec5ed85f":{
      "scriptId":"u26"},
    "26ef8b5d4bb94ff89f72ef8989549dba":{
      "scriptId":"u27"}}});