$axure.loadCurrentPage({
  "url":"系统日志.html",
  "generationDate":new Date(1525962190783.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"396f8d2613b64d1c87a2d8ce5b2bf314",
    "type":"Axure:Page",
    "name":"系统日志",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"02f7fc18f73346308f6279bda63969b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":70,
              "y":160},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bdb54fc569642a8b5d69738bf2f745d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":70,
                  "y":160},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7553a68326c473dae4e94656508d0b1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":130},
            "size":{
              "width":800,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/u118_line.png"}},
{
          "id":"71d772d4d5d04a69900476957e19fe3c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":620,
              "y":197},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c92c9905ded44f13b0a02c4b2b057c35",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":57,
              "y":195},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4f555343b06241b981bef05abfe31f38",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":147,
              "y":195},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"00b00a2cc2464fa3a6056a65e51c8b43",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":257,
              "y":197},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"4b0f8c8636054e13ad2506812759ebb2",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":57,
              "y":260},
            "size":{
              "width":466,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efb12f2093a44f35a24d14384a460243",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7c514948a0ce44ff893fddf8e8c41ca4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u8.png"}},
{
              "id":"161c174e7e6c4bd383a47999119d38c9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cb472f4b5b784e5eb22405dedded8077",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u8.png"}},
{
              "id":"a9078c0da26644c693d503de7580ff70",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed58ac24c6b74ad1ae69257ed593a071",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u28.png"}},
{
              "id":"f4b38be06c0c4fc49deefbed6f473d0e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":93,
                  "y":0},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e37e2e45532d479580df9d28b8456d39",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u8.png"}},
{
              "id":"9507ff38568c42eeb6b87e394178e3c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":93,
                  "y":30},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b46b1fd2ae5c4be8aece6d9f5bdc6789",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":93,
                      "y":30},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u8.png"}},
{
              "id":"cf44b937a9bc41cbbfc5634d06f53cfa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":93,
                  "y":60},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ccf3d8439d1148639d32ec0c05913dba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":93,
                      "y":60},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u28.png"}},
{
              "id":"0dafd8768eb7436ba9d9410be8806269",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":279,
                  "y":0},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b5579099e2c649b0bcda8937c395f584",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":279,
                      "y":0},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u8.png"}},
{
              "id":"4ae2754683a74b6e9d41b6d826d9931c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":279,
                  "y":30},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"35e4c906fc134f7dbe588032a5aeba9b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":279,
                      "y":30},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u8.png"}},
{
              "id":"81f3b6111a4c443e848c96766ab6b40d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":279,
                  "y":60},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f7dddc90dd27410bb795dd645fd383bc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":279,
                      "y":60},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u28.png"}},
{
              "id":"cda46aa51bcd49578d3dd54ebfd33c7f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":0},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"afcfd179a75a446e9a9dd435a6fb5ab9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":0},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u16.png"}},
{
              "id":"af1d0d939f38440d92b37ce1efe5ac37",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":30},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7583b433d7749d0a0f6e8296fb89b6c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":30},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u16.png"}},
{
              "id":"83a9aab4f20e4d38b4a294f5afb7678c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":60},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae21fe1d2913491d9a472fff57de71e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":60},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u36.png"}},
{
              "id":"94b3099693ae4f23999098790021901b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":186,
                  "y":0},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63c7e1f1834a4d25a176b0ab5a812e8a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":186,
                      "y":0},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u8.png"}},
{
              "id":"33faf8ef75354e2690a5a745bba3eee4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":186,
                  "y":30},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a462c7275cd4b1e9258fe7d896b3fea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":186,
                      "y":30},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u8.png"}},
{
              "id":"47af1ec298e049bf8ac0b19762cf3a95",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":186,
                  "y":60},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abafe7c9d72b4efbbd55d4ec8300be10",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":186,
                      "y":60},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/系统日志/u28.png"}}]},
{
          "id":"a629c613bda140d384f139cd15f31e77",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":360,
              "y":196.5},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"98a76b97c8d246779fb5973a11eded83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":70,
              "y":50},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e17c02b4fe14c0d8a907269a3e66660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":70,
                  "y":50},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u2.png"}},
{
          "id":"7bc15fc9630e419486dddf19759b9daa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":200,
              "y":50},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"432c215c6ab544d6b5a29e749b9b51f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":200,
                  "y":50},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 事件查询",
                      "target":{
                        "targetType":"page",
                        "url":"事件查询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u2.png"}},
{
          "id":"3dd9a63c7dca437f86246309718dea5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":340,
              "y":50},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b5e1d993265457faf215afc22258735",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":340,
                  "y":50},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统配置",
                      "target":{
                        "targetType":"page",
                        "url":"系统配置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u2.png"}},
{
          "id":"6cc0d26f023f4145a76e21f9c040db95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF0066CC},
            "location":{
              "x":610,
              "y":50},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74d3eb63b22845f5b0479ccd8fc83f42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066CC},
                "location":{
                  "x":610,
                  "y":50},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统日志",
                      "target":{
                        "targetType":"page",
                        "url":"系统日志.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u0.png"}},
{
          "id":"b69ec89270c942a88f11457d0b5890a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":730,
              "y":50},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d5e8245f8474bdda0078f00ede5c885",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":730,
                  "y":50},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统监控",
                      "target":{
                        "targetType":"page",
                        "url":"系统监控.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u2.png"}},
{
          "id":"c6b9c8be91c54f64b96ffd7ae015c102",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":470,
              "y":50},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74814907542044aca7d7aaf04cacf168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":470,
                  "y":50},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 userManer",
                      "target":{
                        "targetType":"page",
                        "url":"usermaner.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "02f7fc18f73346308f6279bda63969b6":{
      "scriptId":"u0"},
    "1bdb54fc569642a8b5d69738bf2f745d":{
      "scriptId":"u1"},
    "b7553a68326c473dae4e94656508d0b1":{
      "scriptId":"u2"},
    "71d772d4d5d04a69900476957e19fe3c":{
      "scriptId":"u3"},
    "c92c9905ded44f13b0a02c4b2b057c35":{
      "scriptId":"u4"},
    "4f555343b06241b981bef05abfe31f38":{
      "scriptId":"u5"},
    "00b00a2cc2464fa3a6056a65e51c8b43":{
      "scriptId":"u6"},
    "4b0f8c8636054e13ad2506812759ebb2":{
      "scriptId":"u7"},
    "efb12f2093a44f35a24d14384a460243":{
      "scriptId":"u8"},
    "7c514948a0ce44ff893fddf8e8c41ca4":{
      "scriptId":"u9"},
    "f4b38be06c0c4fc49deefbed6f473d0e":{
      "scriptId":"u10"},
    "e37e2e45532d479580df9d28b8456d39":{
      "scriptId":"u11"},
    "94b3099693ae4f23999098790021901b":{
      "scriptId":"u12"},
    "63c7e1f1834a4d25a176b0ab5a812e8a":{
      "scriptId":"u13"},
    "0dafd8768eb7436ba9d9410be8806269":{
      "scriptId":"u14"},
    "b5579099e2c649b0bcda8937c395f584":{
      "scriptId":"u15"},
    "cda46aa51bcd49578d3dd54ebfd33c7f":{
      "scriptId":"u16"},
    "afcfd179a75a446e9a9dd435a6fb5ab9":{
      "scriptId":"u17"},
    "161c174e7e6c4bd383a47999119d38c9":{
      "scriptId":"u18"},
    "cb472f4b5b784e5eb22405dedded8077":{
      "scriptId":"u19"},
    "9507ff38568c42eeb6b87e394178e3c6":{
      "scriptId":"u20"},
    "b46b1fd2ae5c4be8aece6d9f5bdc6789":{
      "scriptId":"u21"},
    "33faf8ef75354e2690a5a745bba3eee4":{
      "scriptId":"u22"},
    "0a462c7275cd4b1e9258fe7d896b3fea":{
      "scriptId":"u23"},
    "4ae2754683a74b6e9d41b6d826d9931c":{
      "scriptId":"u24"},
    "35e4c906fc134f7dbe588032a5aeba9b":{
      "scriptId":"u25"},
    "af1d0d939f38440d92b37ce1efe5ac37":{
      "scriptId":"u26"},
    "c7583b433d7749d0a0f6e8296fb89b6c":{
      "scriptId":"u27"},
    "a9078c0da26644c693d503de7580ff70":{
      "scriptId":"u28"},
    "ed58ac24c6b74ad1ae69257ed593a071":{
      "scriptId":"u29"},
    "cf44b937a9bc41cbbfc5634d06f53cfa":{
      "scriptId":"u30"},
    "ccf3d8439d1148639d32ec0c05913dba":{
      "scriptId":"u31"},
    "47af1ec298e049bf8ac0b19762cf3a95":{
      "scriptId":"u32"},
    "abafe7c9d72b4efbbd55d4ec8300be10":{
      "scriptId":"u33"},
    "81f3b6111a4c443e848c96766ab6b40d":{
      "scriptId":"u34"},
    "f7dddc90dd27410bb795dd645fd383bc":{
      "scriptId":"u35"},
    "83a9aab4f20e4d38b4a294f5afb7678c":{
      "scriptId":"u36"},
    "ae21fe1d2913491d9a472fff57de71e0":{
      "scriptId":"u37"},
    "a629c613bda140d384f139cd15f31e77":{
      "scriptId":"u38"},
    "98a76b97c8d246779fb5973a11eded83":{
      "scriptId":"u39"},
    "7e17c02b4fe14c0d8a907269a3e66660":{
      "scriptId":"u40"},
    "7bc15fc9630e419486dddf19759b9daa":{
      "scriptId":"u41"},
    "432c215c6ab544d6b5a29e749b9b51f6":{
      "scriptId":"u42"},
    "3dd9a63c7dca437f86246309718dea5b":{
      "scriptId":"u43"},
    "5b5e1d993265457faf215afc22258735":{
      "scriptId":"u44"},
    "6cc0d26f023f4145a76e21f9c040db95":{
      "scriptId":"u45"},
    "74d3eb63b22845f5b0479ccd8fc83f42":{
      "scriptId":"u46"},
    "b69ec89270c942a88f11457d0b5890a0":{
      "scriptId":"u47"},
    "6d5e8245f8474bdda0078f00ede5c885":{
      "scriptId":"u48"},
    "c6b9c8be91c54f64b96ffd7ae015c102":{
      "scriptId":"u49"},
    "74814907542044aca7d7aaf04cacf168":{
      "scriptId":"u50"}}});