$axure.loadCurrentPage({
  "url":"事件处置参数配置.html",
  "generationDate":new Date(1525962190697.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"76530482de3645abbdf80b37228affc7",
    "type":"Axure:Page",
    "name":"事件处置参数配置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d2dcdd68abeb49989ad45eb83352f4ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":100,
              "y":80},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63573868c8c141e696caad5bfd71ddd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":100,
                  "y":80},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abe7bc7b19dd4a54a77ee0929f89f4a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":102,
              "y":116},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"621faa6732f64cc799bbd07bc29ba5ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":102,
                  "y":116},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b9a4dc70ec14337a9c9fccc9ca8e3cd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":190,
              "y":115},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8042500b615944fdbc2245c6d547e573",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":191,
              "y":146},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1b8f2a440325431aaff7ddfa5b4379bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":101,
              "y":149},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a7e9aeb822b45cda70f0a97e9fcd7ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":101,
                  "y":149},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8549bafb625a4947893984f0e39ea757",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":97,
              "y":214},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e57b9a28fdc4f6097df98c1859327cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":97,
                  "y":214},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e4b9aae537e411fba4ba4cff1aed71a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":192,
              "y":213},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7567d4d851a242f89335b77958e6c44b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":193,
              "y":244},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b4d92e871f5a4b8a8585109e1d50a38b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":76,
              "y":247},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0e6159d7dae4fe1b242c92792d1d6d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":76,
                  "y":247},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98d9d975141f4965aa7780632c7a1885",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":92,
              "y":277},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16b412ac1d6444f5819f82a53d0f7d7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":92,
                  "y":277},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6ea6066c0954501aecbeef5b91fd28a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":194,
              "y":276},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f530cd551d55415ca6cc2cbe4e7fe9c2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":190,
              "y":177},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"02e7846c66fb409c8eefc3c37180a41b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":97,
              "y":180},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99632ab74ac64dd5b6a759f489d2691d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":97,
                  "y":180},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad7e315b9c6e4c4ea1677bfc3f2ccfc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":440,
              "y":184},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f3f0919827641188c9ac15a1b954fdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":440,
                  "y":184},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f35f870059b040fa874547ad52f06b50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":438,
              "y":115},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd3544514f094086bf9759d3c19a2ca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":438,
                  "y":115},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02f4de9d36514a429468e993e8df5124",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":440,
              "y":151},
            "size":{
              "width":330,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81297981019546b7b5466fe62925de4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":440,
                  "y":151},
                "size":{
                  "width":330,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd2a7ef5c93548589ff81e826434caae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":440,
              "y":217},
            "size":{
              "width":340,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"076835ca31454d57b06b0988caa7ea8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":440,
                  "y":217},
                "size":{
                  "width":340,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"944060b0a8f3424fb43ecb494167b0ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":440,
              "y":247},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd0c0c2d5f47457f8bf28c4e557a37de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":440,
                  "y":247},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0837ece97fe45f99f689a4fb0056478",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":447,
              "y":279},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c81da310c2964942b709e20073fb02af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":447,
                  "y":279},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9ef2efcc1ea4785bb66e0fcf4b042f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":83,
              "y":315},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c31617a4968345c7800a3b625d445f63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":83,
                  "y":315},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d2ec955e84c4faebbd8fa5c7c8831ea",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":195,
              "y":310},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b5b3641243b64b6e9eec1eeca43fdfa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":445,
              "y":314},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03f50bca8de94230aa68cf7f2070ce82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":445,
                  "y":314},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d2dcdd68abeb49989ad45eb83352f4ba":{
      "scriptId":"u0"},
    "63573868c8c141e696caad5bfd71ddd3":{
      "scriptId":"u1"},
    "abe7bc7b19dd4a54a77ee0929f89f4a9":{
      "scriptId":"u2"},
    "621faa6732f64cc799bbd07bc29ba5ae":{
      "scriptId":"u3"},
    "0b9a4dc70ec14337a9c9fccc9ca8e3cd":{
      "scriptId":"u4"},
    "8042500b615944fdbc2245c6d547e573":{
      "scriptId":"u5"},
    "1b8f2a440325431aaff7ddfa5b4379bc":{
      "scriptId":"u6"},
    "4a7e9aeb822b45cda70f0a97e9fcd7ba":{
      "scriptId":"u7"},
    "8549bafb625a4947893984f0e39ea757":{
      "scriptId":"u8"},
    "4e57b9a28fdc4f6097df98c1859327cd":{
      "scriptId":"u9"},
    "3e4b9aae537e411fba4ba4cff1aed71a":{
      "scriptId":"u10"},
    "7567d4d851a242f89335b77958e6c44b":{
      "scriptId":"u11"},
    "b4d92e871f5a4b8a8585109e1d50a38b":{
      "scriptId":"u12"},
    "f0e6159d7dae4fe1b242c92792d1d6d2":{
      "scriptId":"u13"},
    "98d9d975141f4965aa7780632c7a1885":{
      "scriptId":"u14"},
    "16b412ac1d6444f5819f82a53d0f7d7f":{
      "scriptId":"u15"},
    "d6ea6066c0954501aecbeef5b91fd28a":{
      "scriptId":"u16"},
    "f530cd551d55415ca6cc2cbe4e7fe9c2":{
      "scriptId":"u17"},
    "02e7846c66fb409c8eefc3c37180a41b":{
      "scriptId":"u18"},
    "99632ab74ac64dd5b6a759f489d2691d":{
      "scriptId":"u19"},
    "ad7e315b9c6e4c4ea1677bfc3f2ccfc1":{
      "scriptId":"u20"},
    "4f3f0919827641188c9ac15a1b954fdc":{
      "scriptId":"u21"},
    "f35f870059b040fa874547ad52f06b50":{
      "scriptId":"u22"},
    "bd3544514f094086bf9759d3c19a2ca3":{
      "scriptId":"u23"},
    "02f4de9d36514a429468e993e8df5124":{
      "scriptId":"u24"},
    "81297981019546b7b5466fe62925de4f":{
      "scriptId":"u25"},
    "dd2a7ef5c93548589ff81e826434caae":{
      "scriptId":"u26"},
    "076835ca31454d57b06b0988caa7ea8f":{
      "scriptId":"u27"},
    "944060b0a8f3424fb43ecb494167b0ea":{
      "scriptId":"u28"},
    "cd0c0c2d5f47457f8bf28c4e557a37de":{
      "scriptId":"u29"},
    "f0837ece97fe45f99f689a4fb0056478":{
      "scriptId":"u30"},
    "c81da310c2964942b709e20073fb02af":{
      "scriptId":"u31"},
    "c9ef2efcc1ea4785bb66e0fcf4b042f5":{
      "scriptId":"u32"},
    "c31617a4968345c7800a3b625d445f63":{
      "scriptId":"u33"},
    "1d2ec955e84c4faebbd8fa5c7c8831ea":{
      "scriptId":"u34"},
    "b5b3641243b64b6e9eec1eeca43fdfa2":{
      "scriptId":"u35"},
    "03f50bca8de94230aa68cf7f2070ce82":{
      "scriptId":"u36"}}});