$axure.loadCurrentPage({
  "url":"网卡配置.html",
  "generationDate":new Date(1525962190620.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"67dea184bfc4484ca465f43cce491cf0",
    "type":"Axure:Page",
    "name":"网卡配置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e0bf0a3b9bd74f5eb5b6d6b0d9a2983f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":100,
              "y":80},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f7cdfef9c79482f8a99a48d8fa5df9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":100,
                  "y":80},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"100137409019433cb4c79cdf4a22dfb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":102,
              "y":116},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"591adcacc2d84660916fa1281c5aaa4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":102,
                  "y":116},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"851458073fa44d4db29e7b59d9819ed0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":100,
              "y":148},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79dd7962945241a28c3f5ba8c37e3532",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":100,
                  "y":148},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c83958169ec4019a3eb3f3418ace796",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":190,
              "y":115},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f535c862d2fd4966bcd9f78d79243b98",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":191,
              "y":146},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"379941292e184695b83c6ffecd061e54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":190,
              "y":80},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efb506efceb34e2cb3524ba5e3840b76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":190,
                  "y":80},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fd5b5f31acb4ccfa929441056e578bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":249},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de9acd36ff53479da7b3dc880851f8db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":249},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"942858ee9d444828af3da7031f6b7cbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":112,
              "y":285},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00f1ee511b3446e780b54d9f4d8ff349",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":112,
                  "y":285},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"601fde564d4c4c5dbfbc5c67bb9571db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":317},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f82718bd4a94a4fbbbc5eeff35bce41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":317},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9aeabc77e7ec408a868185630d308de9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":200,
              "y":284},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3f067b8c2810493289280e8bde4d684f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":201,
              "y":315},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"419bf4f215e1467c91d811dddc585379",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":200,
              "y":249},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fb3fbbbb2f4459b866f91ee151d8dbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":200,
                  "y":249},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bc0582d56934ea7821c6751ae95ba5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":148,
              "y":440},
            "size":{
              "width":489,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4771af66e7041cbada40ac1fb49f311",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":148,
                  "y":440},
                "size":{
                  "width":489,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e0bf0a3b9bd74f5eb5b6d6b0d9a2983f":{
      "scriptId":"u0"},
    "7f7cdfef9c79482f8a99a48d8fa5df9e":{
      "scriptId":"u1"},
    "100137409019433cb4c79cdf4a22dfb5":{
      "scriptId":"u2"},
    "591adcacc2d84660916fa1281c5aaa4d":{
      "scriptId":"u3"},
    "851458073fa44d4db29e7b59d9819ed0":{
      "scriptId":"u4"},
    "79dd7962945241a28c3f5ba8c37e3532":{
      "scriptId":"u5"},
    "9c83958169ec4019a3eb3f3418ace796":{
      "scriptId":"u6"},
    "f535c862d2fd4966bcd9f78d79243b98":{
      "scriptId":"u7"},
    "379941292e184695b83c6ffecd061e54":{
      "scriptId":"u8"},
    "efb506efceb34e2cb3524ba5e3840b76":{
      "scriptId":"u9"},
    "5fd5b5f31acb4ccfa929441056e578bb":{
      "scriptId":"u10"},
    "de9acd36ff53479da7b3dc880851f8db":{
      "scriptId":"u11"},
    "942858ee9d444828af3da7031f6b7cbd":{
      "scriptId":"u12"},
    "00f1ee511b3446e780b54d9f4d8ff349":{
      "scriptId":"u13"},
    "601fde564d4c4c5dbfbc5c67bb9571db":{
      "scriptId":"u14"},
    "5f82718bd4a94a4fbbbc5eeff35bce41":{
      "scriptId":"u15"},
    "9aeabc77e7ec408a868185630d308de9":{
      "scriptId":"u16"},
    "3f067b8c2810493289280e8bde4d684f":{
      "scriptId":"u17"},
    "419bf4f215e1467c91d811dddc585379":{
      "scriptId":"u18"},
    "8fb3fbbbb2f4459b866f91ee151d8dbe":{
      "scriptId":"u19"},
    "7bc0582d56934ea7821c6751ae95ba5d":{
      "scriptId":"u20"},
    "b4771af66e7041cbada40ac1fb49f311":{
      "scriptId":"u21"}}});